# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daumID', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('address_new', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=40)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_flag', models.BooleanField(default=False)),
                ('failed_falg', models.BooleanField(default=False)),
                ('c_barrier', models.PositiveSmallIntegerField()),
                ('c_floor', models.PositiveSmallIntegerField()),
                ('c_elevator_exist', models.PositiveSmallIntegerField()),
                ('c_elevator_capacity', models.PositiveSmallIntegerField()),
                ('c_chair_movable', models.PositiveSmallIntegerField()),
                ('c_toilet_available', models.PositiveSmallIntegerField()),
                ('c_handicapped_toilet', models.PositiveSmallIntegerField()),
                ('c_parking_lot_exist', models.PositiveSmallIntegerField()),
                ('c_handicapped_parking_lot', models.PositiveSmallIntegerField()),
                ('extra_info', models.TextField(max_length=300)),
                ('p_entrance', models.ImageField(upload_to='')),
                ('p_interior', models.ImageField(upload_to='')),
                ('p_extra_pic1', models.ImageField(upload_to='')),
                ('p_extra_pic2', models.ImageField(upload_to='')),
                ('p_extra_pic3', models.ImageField(upload_to='')),
                ('p_extra_pic4', models.ImageField(upload_to='')),
                ('p_extra_pic5', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bfm.Place'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfm.Place'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bfm.Place'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
