# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfm', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='daumID',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
