# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfm', '0008_auto_20161202_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfm.Place'),
        ),
    ]
