# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfm', '0009_auto_20161203_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='failed_falg',
            new_name='failed_flag',
        ),
    ]
