# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfm', '0013_auto_20170311_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='p_entrance',
            field=models.ImageField(null=True, upload_to='test/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='p_extra_pic1',
            field=models.ImageField(null=True, upload_to='test/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='p_extra_pic2',
            field=models.ImageField(null=True, upload_to='test/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='p_extra_pic3',
            field=models.ImageField(null=True, upload_to='test/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='p_extra_pic4',
            field=models.ImageField(null=True, upload_to='test/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='p_extra_pic5',
            field=models.ImageField(null=True, upload_to='test/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='p_interior',
            field=models.ImageField(null=True, upload_to='test/'),
        ),
    ]
