# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfm', '0014_auto_20170311_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='phone_number',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
