# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfm', '0016_auto_20170319_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daumID', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('address_new', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=40, null=True)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_flag', models.BooleanField(default=False)),
                ('failed_flag', models.BooleanField(default=False)),
                ('c_barrier', models.PositiveSmallIntegerField()),
                ('c_floor', models.PositiveSmallIntegerField(null=True)),
                ('c_elevator_exist', models.PositiveSmallIntegerField(default=0)),
                ('c_elevator_capacity', models.PositiveSmallIntegerField(null=True)),
                ('c_chair_movable', models.PositiveSmallIntegerField(default=0)),
                ('c_toilet_available', models.PositiveSmallIntegerField(default=0)),
                ('c_handicapped_toilet', models.PositiveSmallIntegerField(default=0)),
                ('c_parking_lot_exist', models.PositiveSmallIntegerField(default=0)),
                ('c_handicapped_parking_lot', models.PositiveSmallIntegerField(default=0)),
                ('extra_info', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='c_chair_movable',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='c_elevator_exist',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='c_handicapped_parking_lot',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='c_handicapped_toilet',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='c_parking_lot_exist',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='c_toilet_available',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='placehistory',
            name='groupID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfm.Place'),
        ),
        migrations.AddField(
            model_name='placehistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
