# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfm', '0017_auto_20170319_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlace',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('daumID', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('address_new', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=40, null=True)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('verified_flag', models.BooleanField(default=False)),
                ('failed_flag', models.BooleanField(default=False)),
                ('c_barrier', models.PositiveSmallIntegerField()),
                ('c_floor', models.PositiveSmallIntegerField(null=True)),
                ('c_elevator_exist', models.PositiveSmallIntegerField(null=True)),
                ('c_elevator_capacity', models.PositiveSmallIntegerField(null=True)),
                ('c_chair_movable', models.PositiveSmallIntegerField(null=True)),
                ('c_toilet_available', models.PositiveSmallIntegerField(null=True)),
                ('c_handicapped_toilet', models.PositiveSmallIntegerField(null=True)),
                ('c_parking_lot_exist', models.PositiveSmallIntegerField(null=True)),
                ('c_handicapped_parking_lot', models.PositiveSmallIntegerField(null=True)),
                ('extra_info', models.TextField(max_length=300, null=True)),
                ('p_entrance', models.TextField(max_length=100, null=True)),
                ('p_interior', models.TextField(max_length=100, null=True)),
                ('p_extra_pic1', models.TextField(max_length=100, null=True)),
                ('p_extra_pic2', models.TextField(max_length=100, null=True)),
                ('p_extra_pic3', models.TextField(max_length=100, null=True)),
                ('p_extra_pic4', models.TextField(max_length=100, null=True)),
                ('p_extra_pic5', models.TextField(max_length=100, null=True)),
                ('p_extra_pic6', models.TextField(max_length=100, null=True)),
                ('p_extra_pic7', models.TextField(max_length=100, null=True)),
                ('p_extra_pic8', models.TextField(max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical place',
            },
        ),
        migrations.RemoveField(
            model_name='placehistory',
            name='failed_flag',
        ),
        migrations.AlterField(
            model_name='placehistory',
            name='c_chair_movable',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placehistory',
            name='c_elevator_exist',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placehistory',
            name='c_handicapped_parking_lot',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placehistory',
            name='c_handicapped_toilet',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placehistory',
            name='c_parking_lot_exist',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='placehistory',
            name='c_toilet_available',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
