# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUserModel', '0002_auto_20161109_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cangouser',
            name='nickname',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
