# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUserModel', '0003_auto_20161110_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cangouser',
            name='nickname',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
