# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:23
from __future__ import unicode_literals

import customUserModel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUserModel', '0004_auto_20161110_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cangouser',
            name='profile_pic',
            field=models.ImageField(default='user_profile/default.png', storage=customUserModel.models.OverwriteStorage(), upload_to=customUserModel.models.CangoUser.get_image_path),
        ),
    ]
