# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUserModel', '0006_auto_20170116_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cangouser',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
