# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUserModel', '0009_auto_20170119_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cangouser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
